### ISSUE TITLE
[Bug?] Nemerle grammar file isn't properly highlighted

### ISSUE THREAD

**Issue by TheWitheredStriker** [Nixinova/LightShowSite#2]
Hello, as NL still only accepts YAML files, I have to convert essentially every plist / tmLanguage / JSON / CSON / etc file into YAML. 

This applies also to my fork of Nemerle's TextMate bundle:

```
fileTypes:
- n
keyEquivalent: ^~N
name: Nemerle
patterns:
- begin: (^[ \t]+)?(?=//)
  beginCaptures:
    '1':
      name: punctuation.whitespace.comment.leading.nemerle
  end: (?!\G)
  patterns:
  - begin: //
    beginCaptures:
      '0':
        name: punctuation.definition.comment.nemerle
    end: \n
    name: comment.line.double-slash.nemerle
- begin: /\*
  captures:
    '0':
      name: punctuation.definition.comment.nemerle
  end: \*/
  name: comment.block.nemerle
- match: \b(|false|null|true)\b
  name: constant.language.nemerle
- match: \b(([0-9]+(\.|\_)?[0-9]*(b|bu|d|f|L|LU|m|u|ub|UL)?)|(0(b|o|x)[0-9]+))\b
  name: constant.numeric.nemerle
- match: \b(break|catch|continue|else|finally|for|foreach|if|match|matches|otherwise|repeat|try|unless|when|while)\b
  name: keyword.control.nemerle
- match: (\+|\-|\*|\/|\%)\=?
  name: keyword.operator.nemerle
- match: \b(\_|and|as|assert|async|base|callcomp|checked|do|ensures|expose|fun|get|ignore|implements|in|invariant|is|log|lock|namespace|out|params|partial|ref|requires|return|set|syntax|throw|typeof|unchecked|using|with|whenlogging|where|xml|yield|yieldcomp)\b
  name: keyword.other.nemerle
- match: \b(array|bool|byte|char|class|decimal|double|enum|float|int|interface|list|long|macro|module|object|sbyte|short|string|struct|type|uint|ulong|ushort|variant|void)\b
  name: storage.type.nemerle
- match: \b(abstract|comp|def|defcomp|delegate|enumerable|event|extern|internal|mutable|override|public|private|protected|sealed|static|volatile|virtual|new)\b
  name: storage.modifier.nemerle
- match: this
  name: variable.language.nemerle
- begin: '"'
  beginCaptures:
    '0':
      name: punctuation.definition.string.begin.nemerle
  end: '"'
  endCaptures:
    '0':
      name: punctuation.definition.string.end.nemerle
  name: string.quoted.double.nemerle
  patterns:
  - match: \\(\\|'|\"|a|b|c[A-Z]+|e|f|n|r|u0+[0-9,A-Z]+|v)
    name: constant.character.escape.nemerle
- begin: \$"
  beginCaptures:
    '0':
      name: punctuation.definition.string.begin.nemerle
  end: '"'
  endCaptures:
    '0':
      name: punctuation.definition.string.end.nemerle
  name: string.interpolated.nemerle
  patterns:
  - match: \$[a-z,A-Z]+[a-z,A-Z,0-9]*( |\+|\-|\*|\/|\%)
    name: constant.character.escape
- begin: "'"
  beginCaptures:
    '0':
      name: punctuation.definition.string.begin.nemerle
  end: "'"
  endCaptures:
    '0':
      name: punctuation.definition.string.end.nemerle
  name: string.quoted.single.nemerle
  patterns:
  - match: \\(\\|'|\"|a|b|c[A-Z]+|e|f|n|r|u0+[0-9,A-Z]+|v)
    name: constant.character.escape
scopeName: source.nemerle
uuid: F563968D-4CB3-11DB-9F95-00112474B8F0
```

NL accepts this, but doen't actually highlight the text:

![image](https://user-images.githubusercontent.com/38614982/179921028-00fd3563-af1e-47af-9cc9-cde530893af3.png)

Meanwhile, it still highlights other converted YAML's, like my converted Cython TextMate bundle.

You are evidently very active on GitHub. Please consider looking into this and #1 (which I raised over two weeks ago). Thank you.
